#!/usr/bin/python3

import dbus
import sys

def block(manager, index, block):
	func = manager.BlockIdx

	if (index == "wifi"):
		index = 1
		func = manager.Block
	elif (index == "bluetooth"):
		index = 2
		func = manager.Block
	elif (index == "wwan"):
		index = 5
		func = manager.Block
    
	ret = func(index, block)
	print(ret)

if __name__ == "__main__":

	num_args = len(sys.argv)

	if (num_args != 3):
		print("Usage: %s index 0|1" % (sys.argv[0]))
		exit(1)

	bus = dbus.SystemBus()
	manager = dbus.Interface(bus.get_object('org.freedesktop.URfkill',
						'/org/freedesktop/URfkill'),
				'org.freedesktop.URfkill')
	block(manager, sys.argv[1], int(sys.argv[2]))
